### ISSUE TITLE
OpenInputAsync causes an AccessViolationException on Raspberry Pi 3b+ & .net Core 2.1

### ISSUE THREAD

**Issue by Alix1723** [atsushieno/managed-midi#63]
Here's my code:

```
var access = MidiAccessManager.Default;

            foreach(IMidiPortDetails portdetails in access.Inputs)
            {
                Console.WriteLine($"Input: {portdetails.Name} / ID: {portdetails.Id}");
            }

            Console.WriteLine("Reading events...");
            var input = access.OpenInputAsync(access.Inputs.First(indevice => indevice.Name.Contains("nano")).Id).Result;
            input.MessageReceived += (object sender, MidiReceivedEventArgs e)
               =>
            { Console.WriteLine($"event has: {e.Length}"); }; 

            Console.ReadKey();
            input.CloseAsync();
```

(Where "nano" is a "nanoKEY 2" keyboard) 

Running this ends up with:

`Attempted to read or write protected memory. This is often an indication that other memory is corrupt.`

The same project seems to work fine on Windows 10/x64:
![image](https://user-images.githubusercontent.com/3638723/80886137-a7c69500-8cb5-11ea-876e-b2bf2e68b9ef.png)

**Comment by ahopper** [comment]
I'm seeing the same error on rpi4 with .net6.0 on 32 bit raspbian, on 64 bit it works fine.

**Comment by ahopper** [comment]
The stack trace is
Fatal error. Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)Aborted

**Comment by brentmaxwell** [comment]
I'm seeing this as well on an RPi4 running 32 bit Raspberry OS 12 (bookworm) running .NET 8. Works fine under WSL on my PC.
